### ISSUE TITLE
add issue and PR template

### ISSUE THREAD

**Issue by hdngr** [prjctrft/mantenuto#117]
@ericgold - do you think you could tackle this one?  https://github.com/blog/2111-issue-and-pull-request-templates

There are a lot of good templates out there...  For issues, I like the ones that have "behavior" vs "expected behavior".  That format is super helpful for identifying how to tackle an issue/bug.  What do you think?

**Comment by ericgold** [comment]
@hdngr yep, I will get on this later today.
