### ISSUE TITLE
Add Injury select to /Register/Veteran

### ISSUE THREAD

**Issue by ericgold** [prjctrft/mantenuto#55]
Select for "Combat" and "Non-Combat" injury on /Register/Veteran

![veteransignup](https://user-images.githubusercontent.com/17014726/31259743-f65873fc-a9fd-11e7-8dca-b08d7ce493dc.png)

**Comment by hdngr** [comment]
Boom!  Done!  Try and remember to close the issue when you make the commit e.g. `feat(RegisterForm): adds "injury" option closes #8`
