### ISSUE TITLE
register buttons do not highlight correctly

### ISSUE THREAD

**Issue by hdngr** [prjctrft/mantenuto#81]
Looks like multiple buttons highlight on mouseover.  @JaCorbett do we want a different interaction?

![image](https://user-images.githubusercontent.com/1875033/32986162-6e204870-cc80-11e7-9799-db557afcc927.png)

**Comment by ericgold** [comment]
@hdngr I think it's just that the Active Duty one has the hover styles reversed. It starts out gray and turns black on hover, while the other two are the opposite. Unless I am misunderstanding the issue?

**Comment by JaCorbett** [comment]
I'm out to dinner with my family right now and will visit this.

I would like to see the highlight color be the blue, instead of inverted.

Talk on Slack when I'm home.

- James

**Comment by ericgold** [comment]
closed by #86
