### ISSUE TITLE
Video Chat Text Box

### ISSUE THREAD

**Issue by JaCorbett** [prjctrft/mantenuto#87]
Size is not static. Keep messaging and the text box elongates forever.
 
<img width="1680" alt="screen shot 2017-12-01 at 1 05 10 pm" src="https://user-images.githubusercontent.com/13542625/33497144-eff7ef78-d69a-11e7-8032-5d4743b44c60.png">

**Comment by hdngr** [comment]
Ok, just to be clear on the functionality you want, instead of having the text box grow in length, you you want it to scroll?  Could have sworn that is how it was at one point...  I think I fat fingered the css on that.

**Comment by hdngr** [comment]
@ericgold do you want to jump in on this?

**Comment by ericgold** [comment]
@hdngr yes

**Comment by hdngr** [comment]
@ericgold what's the status on this one?  Pass it to me if you'd like 😃

**Comment by ericgold** [comment]
@hdngr I was trying it a bit last night but didn't really get anywhere. If you have time that might be for the best! Sorry about that :)
