### ISSUE TITLE
Video not turning off - No easy way to exit

### ISSUE THREAD

**Issue by JaCorbett** [prjctrft/mantenuto#91]
The 'X' button should turn off the camera and take us back to the main page ("Talk" and "Listen" buttons). The camera turned off once the page was exited out on the browser. 

<img width="1680" alt="screen shot 2017-12-01 at 1 07 03 pm" src="https://user-images.githubusercontent.com/13542625/33497745-ed892f2a-d69c-11e7-8c68-95c381eee8af.png">

**Comment by hdngr** [comment]
@JaCorbett - I did a little bit of research.  If you are on a mac, the "green light" is the indicator that the camera is running.  The red dot is the indicator that the webpage has access to your camera...  https://stackoverflow.com/questions/26670677/remove-red-icon-after-recording-has-stopped
This will exist until the tab is closed.

One way to get around this is do what google hangout does and open the chat/call page in a new window.  What do you guys think @ericgold @bbenefield89 ?

**Comment by JaCorbett** [comment]
That actually sounds great. It would also be easier for a person to exit a call and not feel as if they are being "watched" or something (there could be guys who are paranoid to that degree).

**Comment by hdngr** [comment]
This is now working via #102
