### ISSUE TITLE
chat icon should be "unread messages" icon when there are unread messages

### ISSUE THREAD

**Issue by hdngr** [prjctrft/mantenuto#95]
![image](https://user-images.githubusercontent.com/1875033/33729290-fc1c1af4-db31-11e7-999a-fcac567357bc.png)

Should display unread chat icon.

**Comment by hdngr** [comment]
@ericgold Can you tackle this one?  I'll send you the icons in slack so you have them in front of you.

**Comment by ericgold** [comment]
@hdngr yep, I will
